name: Release

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: github.head_ref
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  documentation:
    runs-on: ubuntu-latest
    name: documentation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.8.3

      - name: generate documentation
        run: make documentation-ci

      - name: check docs diff
        run: exit $(git status --porcelain doc | wc -l | tr -d " ")
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions: write-all
    needs:
      - lint
      - documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: text-transform.nvim

      - name: tag dev versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d dev || true
          git push origin :dev || true
          git tag -a dev -m "Last Development Release"
          git push origin dev
